version: '3'
services:
  db:
    image: postgres:11
    ports:
      - 32700:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRESS_USER: root
      POSTGRESS_PASSWORD: root
      POSTGRESS_DB: employment_exchange
      POSTGRES_HOST_AUTH_METHOD: trust